[project]
name = "arr-py"
version = "0.1.1"

dependencies = [
    "requests>=2.28.1",
    "pydantic>=1.10.2"
]

description = "Basic API wrapper and utility for the arr world"
readme = "README.md"
requires-python = ">=3.7"
dynamic = ["version"]