name: Python package

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
    branches:
      - 'main'

permissions:
  contents: read

env:
  # Python language version to use This value should also be updated
  # in the testing workflow if changed.
  PYTHON_VERSION: '3.10'


jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest requests pydantic
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          max-line-length: "120"
      - name: Test with pytest
        run: |
          pytest